# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(326, 209)
        MainWindow.setStyleSheet("background: #847296;\n"
"color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 440, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 95, 13))
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.paswsword_label = QtWidgets.QLabel(self.centralwidget)
        self.paswsword_label.setGeometry(QtCore.QRect(100, 50, 108, 13))
        self.paswsword_label.setObjectName("paswsword_label")
        self.generator = QtWidgets.QPushButton(self.centralwidget)
        self.generator.setGeometry(QtCore.QRect(120, 140, 75, 23))
        self.generator.setStyleSheet("colour:blue;\n"
"background:yellow;\n"
"border: 5px solid white;\n"
"border-radius:10px;")
        self.generator.setObjectName("generator")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(130, 70, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 100, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.paswsword_label.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.generator.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 326, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Logika"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.label.setText(_translate("MainWindow", "Генератор паролів"))
        self.paswsword_label.setText(_translate("MainWindow", "Тут буде ваш пароль"))
        self.generator.setText(_translate("MainWindow", "Згенерувати"))
        self.checkBox.setText(_translate("MainWindow", "Букви"))
        self.checkBox_2.setText(_translate("MainWindow", "Цифри"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
